language: go

go:
  - 1.8

go_import_path: github.com/m-lab/downloader

  
# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - PROJECT_NAME_BOX=mlab-sandbox
    - CLUSTER_NAME_BOX=downloader
    - BUCKET_NAME_BOX=maxmind-feed-sandbox
    - PROJECT_NAME_STG=mlab-staging
    - CLUSTER_NAME_STG=downloader
    - BUCKET_NAME_STG=downloader-mlab-staging
    - PROJECT_NAME_PRD=mlab-oti
    - CLUSTER_NAME_PRD=downloader
    - BUCKET_NAME_PRD=downloader-mlab-oti
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - DOCKER_IMAGE_NAME=downloader
    - NODE_ENV=CI

before_deploy:
  - $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl

deploy:
#########################################
## Sandbox
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-sandbox downloader maxmind-feed-sandbox
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push


#########################################
## Staging
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy-staging.sh
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    branch: integration

#########################################
## Production
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy-production.sh
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    branch: master
