language: go

go:
- "1.13"

go_import_path: github.com/m-lab/downloader

before_script:
- go get github.com/mattn/goveralls

script:
- go vet ./...
- go build ./...
- go test ./... -cover=1 -coverprofile=_c.cov
- go test ./... -race
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=_c.cov

# Cache Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"

# Install services
services:
- docker

before_deploy:
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl

deploy:
#########################################
## Sandbox
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-sandbox data-processing-cluster downloader-mlab-sandbox $GCLOUD_SERVICE_KEY_BOX
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push


#########################################
## Staging
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-staging data-processing-cluster downloader-mlab-staging $GCLOUD_SERVICE_KEY_STG
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    branch: master

#########################################
## Production
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-oti data-processing-cluster downloader-mlab-oti $GCLOUD_SERVICE_KEY_PRD
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
