language: go

go:
  - 1.8


  
# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_BOX=mlab-sandbox
    - CLUSTER_NAME_BOX=downloader
    - PROJECT_NAME_STG=<YOUR_PROJECT_NAME>
    - CLUSTER_NAME_STG=<YOUR_CLUSTER_NAME>
    - PROJECT_NAME_PRD=<YOUR_PROJECT_NAME>
    - CLUSTER_NAME_PRD=<YOUR_CLUSTER_NAME>
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - DOCKER_IMAGE_NAME=downloader
    - KUBE_DEPLOYMENT_NAME=downloader
    - KUBE_DEPLOYMENT_CONTAINER_NAME=downloader
    - NODE_ENV=CI

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - ls

deploy:
#########################################
## Sandbox
- provider: script
  script: $TRAVIS_BUILD_DIR/deployment/deploy-sandbox.sh
  skip_cleanup: true
  on:
    repo: m-lab/downloader
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push

