FROM gcr.io/cloud-builders/gcloud

# Fetch recent go version.
ENV GOLANG_VERSION 1.20
ENV GOLANG_DOWNLOAD_URL https://go.dev/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 e54bec97a1a5d230fc2f9ad0880fcbabb5888f30ed9666eca4a91c5a32e86cbc

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
    && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
    && tar -C /usr/local/ -xzf golang.tar.gz \
    && rm golang.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

# Install binaries needed for builds and testing.
RUN apt-get update
RUN apt-get install -y jq gcc netcat
RUN apt install ca-certificates libgnutls30 -y
RUN go install -v github.com/m-lab/gcp-config/cmd/cbif@latest

ENTRYPOINT ["/go/bin/cbif"]
