apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: 'true'
      source: '{{GITHUB_COMMIT}}'
    generation: 2
    labels:
      run: downloader
    name: downloader
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: downloader
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: downloader
        annotations:
          prometheus.io/scrape: 'true'
      spec:
        volumes:
          - name: google-cloud-key
            secret:
              secretName: d-key
        containers:
        - env:
          - name: DOWNLOADER_BUCKET
            value: "{{BUCKET_NAME}}"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          image: gcr.io/mlab-sandbox/downloader:{{GITHUB_COMMIT}}
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          imagePullPolicy: IfNotPresent
          name: downloader
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
