apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    source: '{{GITHUB_COMMIT}}'
  generation: 2
  labels:
    run: downloader
  name: downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      run: downloader
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: downloader
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: downloader-secret
      containers:
      - env:
        - name: DOWNLOADER_BUCKET
          value: "{{BUCKET_NAME}}"
        - name: PROJECT_NAME
          value: {{PROJECT_NAME}}
        - name: MAXMIND_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: downloader-secret
              key: license_key
        image: gcr.io/{{PROJECT_NAME}}/downloader:{{GITHUB_COMMIT}}
        imagePullPolicy: IfNotPresent
        name: downloader
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        parser-node: "true"
